# Generated by Django 4.2.16 on 2024-09-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="onboarding_compelete",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
    ]
